version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tareas_mysql
    restart: always
    environment:
      MYSQL_DATABASE: tareas_db
      MYSQL_USER: tareas_user
      MYSQL_PASSWORD: tareas_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    container_name: tareas_api
    build: .
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tareas_db
      SPRING_DATASOURCE_USERNAME: tareas_user
      SPRING_DATASOURCE_PASSWORD: tareas_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data: